"""
Generate prescription PDFs using reportlab and upload to Supabase Storage.
"""

import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                 Table, TableStyle, HRFlowable)
from services.supabase_client import supabase_admin


def generate_prescription_pdf(
    prescription_id: str,
    doctor_name: str,
    patient_name: str,
    appointment_date: str,
    medicines: list[dict],
    notes: str,
) -> bytes:
    """Generate a prescription PDF and return as bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=18,
        textColor=colors.HexColor("#1a56db"),
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.grey,
    )
    body_style = styles["Normal"]
    label_style = ParagraphStyle(
        "Label",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
    )

    elements = []

    # Header
    elements.append(Paragraph("MedBridge", title_style))
    elements.append(Paragraph("Digital Healthcare Platform", subtitle_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a56db")))
    elements.append(Spacer(1, 0.4 * cm))

    # Doctor & Patient info table
    info_data = [
        [Paragraph("<b>Doctor:</b>", body_style), Paragraph(doctor_name, body_style),
         Paragraph("<b>Date:</b>", body_style), Paragraph(appointment_date, body_style)],
        [Paragraph("<b>Patient:</b>", body_style), Paragraph(patient_name, body_style),
         Paragraph("<b>Rx ID:</b>", body_style), Paragraph(prescription_id[:8].upper(), body_style)],
    ]
    info_table = Table(info_data, colWidths=[3 * cm, 7 * cm, 2.5 * cm, 4 * cm])
    info_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 0.4 * cm))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey))
    elements.append(Spacer(1, 0.4 * cm))

    # Medicines section
    elements.append(Paragraph("Prescription", label_style))
    elements.append(Spacer(1, 0.3 * cm))

    if medicines:
        med_header = ["#", "Medicine", "Dosage", "Frequency", "Duration", "Instructions"]
        med_rows = [med_header]
        for i, med in enumerate(medicines, 1):
            med_rows.append([
                str(i),
                med.get("name", ""),
                med.get("dosage", ""),
                med.get("frequency", ""),
                med.get("duration", ""),
                med.get("instructions", ""),
            ])

        med_table = Table(
            med_rows,
            colWidths=[0.8 * cm, 4.5 * cm, 2.5 * cm, 3 * cm, 2.5 * cm, 3.5 * cm],
        )
        med_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a56db")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f4ff")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d0d7f0")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("PADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(med_table)
    else:
        elements.append(Paragraph("No medicines prescribed.", body_style))

    elements.append(Spacer(1, 0.5 * cm))

    # Notes
    if notes:
        elements.append(Paragraph("Doctor's Notes", label_style))
        elements.append(Spacer(1, 0.2 * cm))
        elements.append(Paragraph(notes, body_style))
        elements.append(Spacer(1, 0.5 * cm))

    # Footer
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey))
    elements.append(Spacer(1, 0.2 * cm))
    elements.append(Paragraph(
        f"Generated by MedBridge on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}. "
        "This is a digital prescription. Keep it safe.",
        subtitle_style,
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()


async def upload_prescription_pdf(
    prescription_id: str,
    pdf_bytes: bytes,
) -> str:
    """Upload PDF to Supabase Storage and return public URL."""
    file_path = f"prescriptions/{prescription_id}.pdf"
    supabase_admin.storage.from_("documents").upload(
        file_path,
        pdf_bytes,
        {"content-type": "application/pdf", "upsert": "true"},
    )
    result = supabase_admin.storage.from_("documents").get_public_url(file_path)
    return result
